### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by travy** [travy/movie-scout#23]
##  Description
Create a settings page where users can specify several of the system defaults.

##  Tasks

- [x] Construct an Activity named SettingsActivity have the layout file simply read "Are you ready to ROCK!!!"
- [x] Create a menu item named Settings
- [x] When the settings menu item is clicked, create an intent which will load the SettingsActivity
- [x] Run the emulator to ensure that the SettingsActivity loads properly and displays the text "Are you ready to Rock!!!"
- [x] Create a Fragment named SettingsFragment which will only display the text "Hello, World" in it
- [x] Update the settings_activity.xml file to load the SettingsFragment
- [x] Run the emulator to ensure that the SettingsFragment is properly loaded and displays the text "Hello, World" when the settings menu item clicked
- [x] Create an XML file named settings.xml
- [x] Add preference options for the MovieDB API's v3 and v4 key to be entered
- [x] Load the XML file into the SettingsFragment
- [x] Get the settings to show as EditText fields in the SettingsFragment
- [x] Move all hard-coded data to a strings.xml resource object
- [x] Configure the app to view the contents of the Settings.xml file and display an error message if the keys do not work
- [x] Deprecate everything in the package com.travistorres.moviescout.utils.configs
- [x] Refactor the app so that settings are only acquired by the Settings.xml file
- [x] Remove the configurations.xml resource file
- [x] Update the MainActivity so that it will automatically update whenever the Settings are changed
- [x] Create a menu for the MovieInfoActivity
- [x] Add a menu item named settings
- [x] When the user clicks the settings menu item an intent should be fired which loads the SettingsActivity
- [x] The MovieInfoActivity should automatically update whenever the Settings are changed
- [x] Add an Up Arrow to the SettingsFragment so that the user can press it to return to the previous page
- [x] Document all classes and ensure Code is up to date with Udacity standards

**Comment by travy** [comment]
Removed the ability for settings page to be reached by the Movie Information Activity.  Seemed unnecessary and introduced unnecessary complications.

**Comment by travy** [comment]
Feature has been merged into the development release
