### ISSUE TITLE
Networking API

### ISSUE THREAD

**Issue by travy** [travy/movie-scout#4]
#  Networking API
##  Description
Design a networking API for communicating with the Movie DB API.  The API should be simply designed to accomplish the needs of the application.  Immediate requirements include the ability to sort the movie list by rating and popularity.

##  Tasks
- [x] Construct URL for retrieving movies by popularity
- [x] Construct URL for retrieving movies by rating
- [x] Establish a connection with the Movie DB 
- [x] Acquire a list by popularity
- [x] Acquire a list by rating

**Comment by travy** [comment]
URL's will be dynamically constructed within the MovieDbUrlBuilder class.  All URL's that are meant for requesting data from MovieDbApi should be constructed using this static class object.
