### ISSUE TITLE
Configurations

### ISSUE THREAD

**Issue by travy** [travy/movie-scout#5]
#  Configurations
##  Description
Provide an XML engine for storing configurations.  The most notable configuration at this time would be the MovieDbApi key.  The configuration should be called configurations.xml (simple yet effective) and read by the ConfigurationsReader static class.  To prevent settings from entering into the source code repository I will use a tactic which I am use to from working with CakePHP, and have a file called configurations.xml-default be saved into the repository and when creating the project simply copy it and rename the copy configurations.xml and add the appropriate key.

Keeping the api key in a separate file prevents the accidental insertion of the key into the source repository.

##  Tasks
- [x] Create a valid XML file called configurations.xml and have a setting called movie_db_api_key_v3
- [x] Develop a Configuration Reader class called ConfigurationsReader which will read the contents of configurations.xml.  If the file cannot be found the class should render some sort of exception and log the event
- [x] Update the README file to inform the Udacity staff how to setup the configurations 
- [x] Incorporate the configurations inside of the MovieDbUrlBuilder since it requires the API key to operate correctly

**Comment by travy** [comment]
Decided to simply ignore all changes made to the configurations.xml file rather than having reviewers copy and paste some template.  This file really shouldn't be changing too often (if ever) so ignoring should provide a simple solution as long as I remember when moving between machines.
